.circleci/config.yml, Makefile
Added Makefile with build and upload and versioning
=> Added CI pipeline

docker-compose.yml
=> changing all tutorials compose to be unique in order to prevent conflict

app.py
=> Update rookout import and usage to new api

README.md
=> Frame dump to snapshot

README.md
https://github.com/Rookout/tutorial-python/issues/16
=> RK-4761 - Update README.md

.jenkins/Jenkinsfile, Dockerfile, Makefile
Updated the args and env vars in Dockerfile.
Added the retrieval of the params in the Jenkins file.
=> RK-5850 - Updated jenkins file and dockerfile

README.md
=> fix bug RK-6113 - tutorial sets bp in invalid line

app.py
this is a part of the bughunt, but I'm fixing this to allow proper cleanup in case we demo this
=> RK-6394 - fix delete todo

app.py
https://github.com/Rookout/deployment-demo/pull/35
deployed jaeger server to staging.
trying to connect tutorial-python to it.
=> Connect tracer to server

.jenkins/Jenkinsfile.test, app.py, utils/logging.py
added logs for the tutorial-python demo
=> RK-7333 - Added logs for the log-tail demo

utils/logging.py
=> RK-7374 - log request headers

utils/logging.py
- changed most of the info logs to debug, for making the logtail more relevant.
- split http header to separate logs, for readability and capacity.
- make the todoStr log a bit more noticeable
- iterate over the returned todos of get_todos and log them
=> RK-7456 - logtail // more logs

.jenkins/Jenkinsfile.test, app.py
=> RK-7759 - Add exception capturing integration to python demo

README.md
=> RK-8652 Update README.md

requirements.txt
https://github.com/Rookout/python-flask/commit/1d3742e48f474aa62af4f92a6c9e18c22ad52fe8
=> RK-9621 - upgrade-flask-opentracing-version

requirements.txt
based on https://github.com/Rookout/python-flask/commit/e56318f9c84978ecdaeaaff4aa819dc86f5509c7
=> RK-9662 - added operation name to context baggage

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
=> RK-12382 - Added a dev container

README.md
Added a note to change the port bindings.
=> RK-12520 - Port 5000 already in use M1 macs

app.py
Make sure add_todo starts in line 95 and ends in 109.
This will fix tests
=> RK-14550 - Make sure add_todo starts in line 95 and ends in 109

.jenkins/Jenkinsfile.test
=> RK-14555 - Update the sha of app.py
